### ISSUE TITLE
Ask 

### ISSUE THREAD

**Issue by Vignonfidele** [Sinyu104/Relay-Selection-based-on-DQN#1]
Hi, how are things? I am a doctoral student in telecommunications and a researcher. My research areas include wireless communication, mainly in the reliability of communication systems. I want to ask if you are basing yourself on a specific scientific article to start the project, or is it an idea you came up with?

**Comment by Sinyu104** [comment]
Hi, greedings from Taiwan. Thanks for your attention to this project. I'm a graduated MS student in wireless communication, with more focus on cooperative communication networks. This work is extended from my previous work, "[Relay Selection for Energy Harvesting Relays With Energy Prioritization and Inter-Relay Charging](https://ieeexplore.ieee.org/abstract/document/9805690)", which leverages the DRL model to select the proper relays aiming to minimize the average AoI of the relaying system. It will be summited to the IEEE Wireless Communication Letter recently.

**Comment by Vignonfidele** [comment]
Thanks for the reply. I quickly reviewed the article. Congratulations from el artigues, the results are very good. Is there a public github for that work ''Relay Selection For Energy Harvesting Relays with
Energy Prioritization and Inter-Relay Charging''?

**Comment by Sinyu104** [comment]
Yes, the reproducible code can be found here. -> https://github.com/Sinyu104/EPRS-Relay-Selection-Scheme

**Comment by 620824asd** [comment]
学长，您好，代码缺少Max_link.py，请问您可以补全缺失吗？
Traceback (most recent call last):
  File "E:\PythonProject\Average AoI Minimization for Energy Harvesting\dqn.py", line 6, in <module>
    import environment as Env
  File "E:\PythonProject\Average AoI Minimization for Energy Harvesting\environment.py", line 15, in <module>
    import Max_link as MLink
ModuleNotFoundError: No module named 'Max_link'
